### PR TITLE
Updated OpenFBX and improved FBX importer to acknowledge multiple materials in a single mesh.

### PR DESCRIPTION
**Pull request by IvarPD**
Hello!

Wanted to use the material ID on merged meshes, noticed that they were all using the same material.

This pull request updated OpenFBX and updates the importer to take this into account.

### CODE REVIEW

**Comment by Atrix256** [comment]
Thanks so much for this, I'll get it integrated as soon as I can :)

**Comment by IvarPD** [comment]
Accidentally did a git mess up and another commit was added to this pull request, adding render doc support.

Is it ok if it gets merged with this pull request?

I am more familiar with RenderDoc, so I wanted in-application support for it, like with PIX.
RenderDoc will only be availiable when launching the viewer with -renderdoc as a commandline option, as loading the RenderDoc dll will force disable HW RayTracing.

Thanks!

**Comment by Atrix256** [comment]
FYI i have this in our internal repo and should be able to get it out here and cut a new build tomorrow.
Thanks a lot for these nice changes!

**Comment by Atrix256** [comment]
Code flows from the internal repo to external, so I put your changes in the internal repo before merging them into this public one.
This work is in changelist https://github.com/electronicarts/gigi/commit/ff062f29a889d37a37980f5bfab288806ac4d7d7 and is part of release and tag v0.99.3.

Thanks for these very nice features :)

**Pull request closed without merging**
